#!/usr/bin/env python3

import argparse
from secretservice.logger import *
from secretservice.boto_wrapper import *


def parse_args():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("-v", "--verbosity",
                        help="logging verbosity",
                        type=LogLevel.__getitem__,
                        choices=list(LogLevel),
                        default=LogLevel.info)
    parser.add_argument("-p", "--profile",
                        help="AWS Profile",
                        default=None)

    return parser.parse_args()


def main():

    mainLogger, args = handle_arguments(parse_args())
    mainLogger.info("Hello World!")

def handle_arguments(args):
    mainLogger = setup_logger('MAIN', args.verbosity)
    if args.profile:
        mainLogger.debug("Setting profile to {}".format(args.profile))
        set_aws_profile(profile=args.profile)
    return mainLogger, args


if __name__ == '__main__':
    main()
